name: Run Mean Reversion Trading Bot

on:
  schedule:
    # Runs at 9:30 AM EST / 14:30 UTC, Monday–Friday
    - cron: '30 14 * * 1-5'

jobs:
  trade:
    runs-on: ubuntu-latest
    timeout-minutes: 360  # Max 6 hours

    env:
      ALPACA_API_KEY: ${{ secrets.ALPACA_API_KEY }}
      ALPACA_SECRET_KEY: ${{ secrets.ALPACA_SECRET_KEY }}
      ALPACA_BASE_URL: ${{ secrets.ALPACA_BASE_URL }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yfinance alpaca-trade-api pandas numpy pytz

      - name: Run trading bot
        run: python main.py
